    // let list=document.getElementById("myList");
    // console.dir(list);  
    // let paragraph=document.getElementsByClassName("DOM"); 
    //     console.dir(paragraph);
    //     console.log(paragraph);
    // let  tag= document.getElementsByTagName("p");
    // console.dir(tag);
    // console.log(tag);        
    // let firstElement=document.querySelector("p");
    // console.dir(firstElement);      
    // let allElements=document.querySelectorAll("p");
    // console.dir(allElements);
    // let firstElement=document.querySelector(".DOM");
    // console.dir(firstElement);       
    // let allElements=document.querySelectorAll(".DOM");
    // console.dir(allElements);
    let firstElement=document.querySelector("div");
    console.dir(firstElement);      
    let allElements=document.querySelectorAll("div");
    console.dir(allElements);                  
    